### ISSUE TITLE
Escape atoms via cli

### ISSUE THREAD

**Issue by williamthome** [max-au/erlperf#31]
For example:
```console
./erlperf 'maps:get('Foo', #{'Foo' => bar}).'
```

The below didn't work:
```console
./erlperf 'maps:get(\'Foo\', #{\'Foo\' => bar}).'
```

My workaround:
```console
./erlperf 'maps:get(binary_to_atom(<<"Foo">>), #{binary_to_atom(<<"Foo">>) => bar}).'
```

Is it possible to use/escape single quotes via the terminal?

**Comment by max-au** [comment]
Sorry for the long reply.
It is absolutely possible to use single quotes in the shell. However, escaping rules are different between various shell implementations. For example, Ubuntu 22 with `bash` allows me to run your first example using double-quotes this way:
```bash
./erlperf "maps:get('Foo', #{'Foo' => bar})."
```

See more on single-quite: http://www.gnu.org/software/bash/manual/html_node/Single-Quotes.html

Likely, you're using `bash`, and therefore, single quote is not allowed within the quoted text. Still, if you're _very_ much in favour of single quote, you could use it this way:
```bash
./erlperf 'maps:get('"'"'Foo'"'"', #{'"'"'Foo'"'"' => bar}).'
```
To explain what is happening with '"'"': first single quote ends the previous (partial) line, then, there is double quote opening the next partial line, that only has a single quote, followed by double quote. Then, another single-quoted line follows. In essence, you'd need to replace all the single-quote characters with '"'"' sequence.

Or, you could use double-quote: https://www.gnu.org/software/bash/manual/html_node/Double-Quotes.html which in turn would require you to escape following characters: ‘$’, ‘`’, ‘\’, and, when history expansion is enabled, ‘!’

Pick your poison :)
Other shell have different interpolation rules (e.g. Windows PowerShell).

While this isn't a bug per se, ruminating over it led me to another useful consideration. I think `erlperf` can benefit from a command-line switch that will make it produce an `*.erl` file containing actual generated module. So that it's easy to see where shell escaping screwed things up...

**Comment by williamthome** [comment]
Very nice and clear explanation. Thanks, @max-au!
